on:
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C3
    outputs:
     stylegan2Ada:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/gradient-ai/stylegan2-ada.git
  StyleGan2Ada:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      stylegan2Ada: CloneRepo.outputs.stylegan2Ada
    outputs:
      generatedFaces:
        type: dataset
        with:
          ref: demo-dataset
    uses: script@v1
    with:
      script: |-
        pip install scipy==1.3.3
        pip install requests==2.22.0
        pip install Pillow==6.2.1
        pip install h5py==2.9.0
        pip install imageio==2.9.0
        pip install imageio-ffmpeg==0.4.2
        pip install tqdm==4.49.0

        cd /inputs/stylegan2
      
        python run_generator.py generate-images \
          --network=gdrive:networks/stylegan2-ffhq-config-f.pkl \
          --seeds=6600-6605 \
          --truncation-psi=0.5 \
          --result-dir=/outputs/generatedFaces
      image: nvcr.io/nvidia/tensorflow:20.10-tf1-py3

